"""The 19 Core v1 protocols (Active Contract section 7.2).

Roster and count come from spec/protocols.yaml; every type in a signature is
resolved by spec/protocol_types.yaml. Generated by tools/generate_protocols.py.
"""
from __future__ import annotations

from evolution_engine.protocols.audit import AuditLog
from evolution_engine.protocols.deployment import DeploymentManager
from evolution_engine.protocols.evidence import EvidenceStore
from evolution_engine.protocols.lineage import LineageRepository
from evolution_engine.protocols.measurement import MetricRunner
from evolution_engine.protocols.mutation import MutationEngine, MutationStrategy
from evolution_engine.protocols.policy import PolicyEngine
from evolution_engine.protocols.population import PopulationManager
from evolution_engine.protocols.project import ProjectAdapter
from evolution_engine.protocols.recovery import CheckpointManager, RecoveryManager
from evolution_engine.protocols.representation import SourceAnalyzer
from evolution_engine.protocols.sandbox import SandboxManager
from evolution_engine.protocols.selection import ParetoSelector
from evolution_engine.protocols.storage import ArtifactStore
from evolution_engine.protocols.testing import CapabilityVerifier, OracleRunner, TestRunner

__all__ = [
    "ArtifactStore",
    "AuditLog",
    "CapabilityVerifier",
    "CheckpointManager",
    "DeploymentManager",
    "EvidenceStore",
    "LineageRepository",
    "MetricRunner",
    "MutationEngine",
    "MutationStrategy",
    "OracleRunner",
    "ParetoSelector",
    "PolicyEngine",
    "PopulationManager",
    "ProjectAdapter",
    "RecoveryManager",
    "SandboxManager",
    "SourceAnalyzer",
    "TestRunner",
]
