"""Audit protocols. Generated by tools/generate_protocols.py."""
from __future__ import annotations

from typing import Protocol

from evolution_engine.types import (
    ArtifactId,
    AuditReceipt,
)

class AuditLog(Protocol):
    """Active Contract section 7.2. Returns AuditReceipt."""

    def append(self, event_type: str, actor: str, payload_artifact_id: ArtifactId) -> AuditReceipt:
        ...
