"""Deployment protocols. Generated by tools/generate_protocols.py."""
from __future__ import annotations

from typing import Protocol

from evolution_engine.types import (
    ArtifactId,
    DeploymentResult,
)

class DeploymentManager(Protocol):
    """Active Contract section 7.2. Returns DeploymentResult."""

    def deploy(self, artifact_id: ArtifactId, mode: str) -> DeploymentResult:
        ...
