"""Evidence protocols. Generated by tools/generate_protocols.py."""
from __future__ import annotations

from typing import Protocol

from evolution_engine.types import (
    ArtifactId,
    EvidenceRecord,
)

class EvidenceStore(Protocol):
    """Active Contract section 7.2. Returns EvidenceRecord."""

    def record(self, evidence_type: str, artifact_id: ArtifactId) -> EvidenceRecord:
        ...
