"""Lineage protocols. Generated by tools/generate_protocols.py."""
from __future__ import annotations

from typing import Protocol

from evolution_engine.types import (
    LineageSnapshot,
    RunId,
)

class LineageRepository(Protocol):
    """Active Contract section 7.2. Returns LineageSnapshot."""

    def snapshot(self, run_id: RunId) -> LineageSnapshot:
        ...
