"""Measurement protocols. Generated by tools/generate_protocols.py."""
from __future__ import annotations

from typing import Protocol

from evolution_engine.types import (
    CandidateId,
    MetricResult,
    SchemaDocument,
)

class MetricRunner(Protocol):
    """Active Contract section 7.2. Returns MetricResult."""

    def measure(self, candidate_id: CandidateId, objective: SchemaDocument) -> MetricResult:
        ...
