"""Mutation protocols. Generated by tools/generate_protocols.py."""
from __future__ import annotations

from typing import Protocol

from evolution_engine.types import (
    CandidateDrafts,
    MutationContext,
    MutationResult,
    PopulationManifest,
    ProgramRepresentation,
)

class MutationStrategy(Protocol):
    """Active Contract section 7.2. Returns MutationResult."""

    def propose(self, parent: ProgramRepresentation, context: MutationContext) -> MutationResult:
        ...


class MutationEngine(Protocol):
    """Active Contract section 7.2. Returns CandidateDrafts."""

    def draft_candidates(self, population: PopulationManifest) -> CandidateDrafts:
        ...
