"""Policy protocols. Generated by tools/generate_protocols.py."""
from __future__ import annotations

from typing import Protocol

from evolution_engine.types import (
    CandidateArtifact,
    PolicyVerdict,
)

class PolicyEngine(Protocol):
    """Active Contract section 7.2. Returns PolicyVerdict."""

    def evaluate(self, artifact: CandidateArtifact) -> PolicyVerdict:
        ...
