"""Population protocols. Generated by tools/generate_protocols.py."""
from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from evolution_engine.types import (
    CandidateArtifact,
    PopulationManifest,
    SelectionDecision,
)

class PopulationManager(Protocol):
    """Active Contract section 7.2. Returns PopulationManifest."""

    def advance(self, candidates: Sequence[CandidateArtifact], decisions: Sequence[SelectionDecision]) -> PopulationManifest:
        ...
