"""Project protocols. Generated by tools/generate_protocols.py."""
from __future__ import annotations

from pathlib import Path
from typing import Protocol

from evolution_engine.types import (
    ProjectManifest,
)

class ProjectAdapter(Protocol):
    """Active Contract section 7.2. Returns ProjectManifest."""

    def load_project(self, project_path: Path) -> ProjectManifest:
        ...
