"""Recovery protocols. Generated by tools/generate_protocols.py."""
from __future__ import annotations

from typing import Protocol

from evolution_engine.types import (
    CheckpointManifest,
    GenerationId,
    RecoveryManifest,
    RunId,
)

class CheckpointManager(Protocol):
    """Active Contract section 7.2. Returns CheckpointManifest."""

    def checkpoint(self, run_id: RunId, generation_id: GenerationId) -> CheckpointManifest:
        ...


class RecoveryManager(Protocol):
    """Active Contract section 7.2. Returns RecoveryManifest."""

    def recover(self, checkpoint: CheckpointManifest) -> RecoveryManifest:
        ...
