"""Representation protocols. Generated by tools/generate_protocols.py."""
from __future__ import annotations

from pathlib import Path
from typing import Protocol

from evolution_engine.types import (
    ProgramRepresentation,
)

class SourceAnalyzer(Protocol):
    """Active Contract section 7.2. Returns ProgramRepresentation."""

    def analyze(self, source_root: Path) -> ProgramRepresentation:
        ...
