"""Sandbox protocols. Generated by tools/generate_protocols.py."""
from __future__ import annotations

from typing import Protocol

from evolution_engine.types import (
    CandidateArtifact,
    SandboxExecutionResult,
    SandboxRequest,
)

class SandboxManager(Protocol):
    """Active Contract section 7.2. Returns SandboxExecutionResult."""

    def execute(self, artifact: CandidateArtifact, request: SandboxRequest) -> SandboxExecutionResult:
        ...
