"""Selection protocols. Generated by tools/generate_protocols.py."""
from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from evolution_engine.types import (
    CandidateId,
    SchemaDocument,
    SelectionDecision,
)

class ParetoSelector(Protocol):
    """Active Contract section 7.2. Returns SelectionDecision."""

    def select(self, eligible: Sequence[CandidateId], objectives: Sequence[SchemaDocument]) -> SelectionDecision:
        ...
