"""Storage protocols. Generated by tools/generate_protocols.py."""
from __future__ import annotations

from typing import Protocol

from evolution_engine.types import (
    ArtifactRef,
)

class ArtifactStore(Protocol):
    """Active Contract section 7.2. Returns ArtifactRef."""

    def put(self, data: bytes, media_type: str) -> ArtifactRef:
        ...
