"""Testing protocols. Generated by tools/generate_protocols.py."""
from __future__ import annotations

from typing import Protocol

from evolution_engine.types import (
    CandidateArtifact,
    CandidateId,
    CapabilityVerdict,
    OracleResult,
    SchemaDocument,
    TestPlan,
    TestSuiteResult,
)

class TestRunner(Protocol):
    """Active Contract section 7.2. Returns TestSuiteResult."""

    def run_tests(self, artifact: CandidateArtifact, plan: TestPlan) -> TestSuiteResult:
        ...


class CapabilityVerifier(Protocol):
    """Active Contract section 7.2. Returns CapabilityVerdict."""

    def verify(self, results: TestSuiteResult, contract: SchemaDocument) -> CapabilityVerdict:
        ...


class OracleRunner(Protocol):
    """Active Contract section 7.2. Returns OracleResult."""

    def check(self, candidate_id: CandidateId, plan: TestPlan) -> OracleResult:
        ...
