#!/usr/bin/env python3
"""Generate the canonical integrity triggers (REQ-S13-003).

The owner_type -> (table, primary key) mapping is derived from the DDL itself, so
a trigger can never name a table or column that does not exist. The previous
hand-written set referenced a table `evaluations` and a column `NEW.seq`, neither
of which is in the schema, and every INSERT into artifact_refs failed as a result.

Output is written into spec/ACTIVE_CONTRACT.md section 13.2 as a normative block.
"""
from __future__ import annotations

import pathlib
import re
import sqlite3
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DDL_DOC = ROOT / "docs/03_storage_and_database/SQLITE_DDL_29_TABLES.md"
CONTRACT = ROOT / "spec/ACTIVE_CONTRACT.md"

OWNER_TABLES = {
    "PROJECT": "projects", "RUN": "runs", "GENERATION": "generations",
    "CANDIDATE": "candidates", "MUTATION_ATTEMPT": "mutation_attempts",
    "EVALUATION_ATTEMPT": "evaluation_attempts", "TEST_RESULT": "test_results",
    "CAPABILITY_RESULT": "capability_results", "METRIC_RESULT": "metric_results",
    "ORACLE_RESULT": "oracle_results", "SELECTION_DECISION": "selection_decisions",
    "CHECKPOINT": "checkpoints", "RECOVERY": "recovery_records",
    "EVIDENCE": "evidence_records", "AUDIT": "audit_events", "DEPLOYMENT": "deployments",
}
MARKER_BEGIN = "<!-- INTEGRITY_TRIGGERS_BEGIN -->"
MARKER_END = "<!-- INTEGRITY_TRIGGERS_END -->"


def ddl_sql() -> str:
    blocks, current = [], None
    for line in DDL_DOC.read_text(encoding="utf-8").split("\n"):
        if line.startswith("```"):
            if current is None:
                current = []
            else:
                blocks.append("\n".join(current))
                current = None
            continue
        if current is not None:
            current.append(line)
    return "\n".join(b for b in blocks if "CREATE TABLE" in b or "CREATE INDEX" in b)


def build(sql: str) -> str:
    con = sqlite3.connect(":memory:")
    con.executescript(sql)
    declared = set(re.findall(r"'([A-Z_]+)'", re.search(
        r"owner_type TEXT NOT NULL CHECK\(owner_type IN \((.*?)\)\)", sql, re.S).group(1)))
    if declared != set(OWNER_TABLES):
        raise SystemExit(
            f"owner_type CHECK and the mapping disagree: "
            f"check-only={sorted(declared - set(OWNER_TABLES))} "
            f"map-only={sorted(set(OWNER_TABLES) - declared)}")

    cases = []
    for owner in sorted(OWNER_TABLES):
        table = OWNER_TABLES[owner]
        pk = [c[1] for c in con.execute(f'PRAGMA table_info("{table}")') if c[5]]
        if len(pk) != 1:
            raise SystemExit(f"{table} has primary key {pk}; expected exactly one column")
        cases.append(
            f"        WHEN NEW.owner_type = '{owner}' AND NOT EXISTS (\n"
            f"                 SELECT 1 FROM {table} WHERE {pk[0]} = NEW.owner_id)\n"
            f"             THEN RAISE(ABORT, 'artifact_refs: owner_id not found in {table}')")

    body = "\n".join(cases)
    return f"""```sql
-- Integrity triggers (REQ-S13-003). Generated by tools/generate_integrity_triggers.py
-- from the DDL above; the owner_type -> table mapping is read out of the schema so a
-- trigger cannot reference a table or column that does not exist.

-- 1. Polymorphic owner validation for artifact_refs, covering all {len(OWNER_TABLES)} owner types.
CREATE TRIGGER trg_artifact_refs_owner_exists
BEFORE INSERT ON artifact_refs
FOR EACH ROW
BEGIN
    SELECT CASE
{body}
    END;
END;

-- 2. Audit chain sequence must advance by exactly one, per run scope.
--    run_id IS NULL is the engine scope and is counted separately.
CREATE TRIGGER trg_audit_events_sequence_is_gapless
BEFORE INSERT ON audit_events
FOR EACH ROW
BEGIN
    SELECT CASE
        WHEN NEW.sequence_no != (
                 SELECT COALESCE(MAX(sequence_no) + 1, 0) FROM audit_events
                 WHERE run_id IS NEW.run_id)
             THEN RAISE(ABORT, 'audit_events: sequence_no must advance by exactly 1 with no gap')
    END;
END;

-- 3. A candidate in a terminal state is immutable.
CREATE TRIGGER trg_candidates_terminal_is_immutable
BEFORE UPDATE OF source_hash, generation_id, source_artifact_id ON candidates
FOR EACH ROW
WHEN OLD.candidate_state IN ('SELECTED', 'REJECTED', 'QUARANTINED')
BEGIN
    SELECT RAISE(ABORT, 'candidates: a terminal candidate cannot be modified');
END;

-- 4. Lineage must not contain a direct self loop.
CREATE TRIGGER trg_lineage_edges_no_self_loop
BEFORE INSERT ON lineage_edges
FOR EACH ROW
WHEN NEW.parent_candidate_id = NEW.child_candidate_id
BEGIN
    SELECT RAISE(ABORT, 'lineage_edges: a candidate cannot be its own parent');
END;
```"""


def main() -> int:
    sql = ddl_sql()
    triggers = build(sql)

    # prove the generated triggers install and behave before writing them anywhere
    con = sqlite3.connect(":memory:")
    con.execute("PRAGMA foreign_keys=ON")
    con.executescript(sql)
    con.executescript(re.search(r"```sql\n(.*?)```", triggers, re.S).group(1))
    con.execute("INSERT INTO artifacts VALUES('a','s',1,'m','p','t')")
    con.execute("INSERT INTO projects VALUES('p','n','1','t')")
    cols = len([c for c in con.execute("PRAGMA table_info(artifact_refs)")])
    con.execute("INSERT INTO artifact_refs VALUES(" +
                ",".join(["'r1'", "'PROJECT'", "'p'", "'a'"] + ["'role'"] * (cols - 4)) + ")")
    try:
        con.execute("INSERT INTO artifact_refs VALUES(" +
                    ",".join(["'r2'", "'PROJECT'", "'ghost'", "'a'"] + ["'role'"] * (cols - 4)) + ")")
        raise SystemExit("self-check failed: a dangling owner_id was accepted")
    except sqlite3.IntegrityError:
        pass

    body = CONTRACT.read_text(encoding="utf-8")
    block = f"{MARKER_BEGIN}\n\n{triggers}\n\n{MARKER_END}"
    if MARKER_BEGIN in body:
        body = re.sub(re.escape(MARKER_BEGIN) + r".*?" + re.escape(MARKER_END), block, body, flags=re.S)
    else:
        anchor = "\n---\n\n# 14. Atomic Commit"
        if anchor not in body:
            raise SystemExit("cannot find the end of section 13 to append the triggers")
        body = body.replace(anchor, f"\n{block}\n{anchor}", 1)
    CONTRACT.write_text(body, encoding="utf-8")
    print(f"wrote integrity triggers into spec/ACTIVE_CONTRACT.md — "
          f"{len(OWNER_TABLES)} owner types, self-check passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
